name: id-demo
on: 
  push:
    branches:
      - main
      - dev
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: run if branch is main
        if: github.ref == 'refs/heads/main'
        run: echo "Running this step"
      - name: running the step directly
        run: echo "Meow Meow run"        
