name: gha-script

on:
  push:
    branches:
      - main
      - develop
      - feature/pr-demo
      - release/**'
  pull_request:
    branches:
      - main
      - develop
      - feature/pr-demo
      - release/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build step
        run: echo "Hello from deployment master, ${{ secrets.MY_NAME }}"
